import { describe, expect, it } from 'vitest';
import { ProjectImportDocumentSchema } from './project-import.schema';

const PROJECT_ID = 'clwproject0000000000000001';
const TABLE_ID = 'clwtable00000000000000001';
const FIELD_ID = 'clwfield00000000000000001';
const INDEX_ID = 'clwindex00000000000000001';

describe('ProjectImportDocumentSchema', () => {
  it('parses export-shaped document', () => {
    const doc = {
      format: 'sxgerador-project',
      formatVersion: 1,
      exportedAt: '2026-05-12T10:00:00.000Z',
      project: {
        id: PROJECT_ID,
        name: 'Meu projeto',
        slug: 'meu-projeto',
        description: null,
        visibility: 'PRIVATE',
        ownerUserId: 'clwuser00000000000000001',
        ownerTeamId: null,
        defaultTamFil: 2,
        defaultLang: 'pt-BR',
        createdAt: new Date('2026-01-01T00:00:00.000Z'),
        updatedAt: new Date('2026-01-01T00:00:00.000Z'),
        deletedAt: null,
      },
      tables: [
        {
          id: TABLE_ID,
          projectId: PROJECT_ID,
          prefix: 'ZZZ',
          fileName: 'ZZZ010',
          namePt: 'Teste',
          nameEs: null,
          nameEn: null,
          routine: null,
          modeCompany: 'C',
          modeUnit: 'C',
          modeBranch: 'C',
          ttsEnabled: 'S',
          uniqueKey: 'ZZZ_FILIAL+ZZZ_COD',
          pyme: 'N',
          modules: 0,
          hasClob: 'N',
          autoIncRec: 'N',
          tamFil: 2,
          tamUn: 2,
          tamEmp: 2,
          notes: null,
          createdAt: new Date('2026-01-01T00:00:00.000Z'),
          updatedAt: new Date('2026-01-01T00:00:00.000Z'),
          deletedAt: null,
          fields: [
            {
              id: FIELD_ID,
              tableId: TABLE_ID,
              name: 'ZZZ_FILIAL',
              order: '01',
              type: 'C',
              size: 2,
              decimals: 0,
              titlePt: 'Filial',
              titleEs: null,
              titleEn: null,
              descPt: 'Filial',
              descEs: null,
              descEn: null,
              picture: '@!',
              pictureVar: null,
              pictureBrowse: null,
              validation: null,
              userValidation: null,
              defaultRel: "xFilial('ZZZ')",
              whenExpr: null,
              initBrowse: null,
              comboPt: null,
              comboEs: null,
              comboEn: null,
              searchKey: null,
              visualMode: 'A',
              contextMode: 'R',
              owner: 'U',
              required: null,
              showBrowse: 'S',
              hasCheck: 'N',
              hasTrigger: 'N',
              level: 0,
              pyme: 'N',
              serverIndex: 'N',
              fieldIndex: 'N',
              spelling: 'N',
              modal: 'N',
              positionLogix: 'N',
              usadoFlags: {},
              modulesFlags: {},
              sqlCondition: null,
              sqlCheck: null,
              groupSxg: null,
              folder: null,
              screen: null,
              grouping: null,
              reserved: null,
              notes: null,
              createdAt: new Date('2026-01-01T00:00:00.000Z'),
              updatedAt: new Date('2026-01-01T00:00:00.000Z'),
              deletedAt: null,
            },
            {
              id: 'clwfield00000000000000002',
              tableId: TABLE_ID,
              name: 'ZZZ_COD',
              order: '02',
              type: 'C',
              size: 10,
              decimals: 0,
              titlePt: 'Codigo',
              titleEs: null,
              titleEn: null,
              descPt: 'Codigo',
              descEs: null,
              descEn: null,
              picture: '@!',
              pictureVar: null,
              pictureBrowse: null,
              validation: null,
              userValidation: null,
              defaultRel: null,
              whenExpr: null,
              initBrowse: null,
              comboPt: null,
              comboEs: null,
              comboEn: null,
              searchKey: null,
              visualMode: 'A',
              contextMode: 'R',
              owner: 'U',
              required: null,
              showBrowse: 'S',
              hasCheck: 'N',
              hasTrigger: 'N',
              level: 0,
              pyme: 'N',
              serverIndex: 'N',
              fieldIndex: 'N',
              spelling: 'N',
              modal: 'N',
              positionLogix: 'N',
              usadoFlags: {},
              modulesFlags: {},
              sqlCondition: null,
              sqlCheck: null,
              groupSxg: null,
              folder: null,
              screen: null,
              grouping: null,
              reserved: null,
              notes: null,
              createdAt: new Date('2026-01-01T00:00:00.000Z'),
              updatedAt: new Date('2026-01-01T00:00:00.000Z'),
              deletedAt: null,
            },
          ],
          indexes: [
            {
              id: INDEX_ID,
              tableId: TABLE_ID,
              order: '1',
              key: 'ZZZ_FILIAL+ZZZ_COD',
              descPt: 'Principal',
              descEs: null,
              descEn: null,
              owner: 'U',
              searchExpr: null,
              nickname: null,
              showSearch: 'S',
              isVirtual: 'N',
              virtualCustomizable: 'N',
              notes: null,
              createdAt: new Date('2026-01-01T00:00:00.000Z'),
              updatedAt: new Date('2026-01-01T00:00:00.000Z'),
              deletedAt: null,
            },
          ],
        },
      ],
    };

    const parsed = ProjectImportDocumentSchema.parse(doc);
    expect(parsed.tables).toHaveLength(1);
    expect(parsed.tables[0].fields[0].name).toBe('ZZZ_FILIAL');
  });
});
